"""Convert Oxford Dictionary of English 2024 (ODE now opus build) to Yomitan.

This is a separate converter from ldoce2yomitan.py -- ODE 2024's markup shares
nothing with LDOCE5's, and forcing both into one file would couple two unrelated
grammars. It reuses the same output contract (format-3 term bank + SC glossary).

ODE 2024's structure, verified by dumping real entries (converter/_ode_struct.py):

    div.entryPageContent
      header.entryHeader
        h2.pageTitle > span.realTitle        the headword
        a.icon-audio                         the audio link (sound://)
        div.headpron                         the pronunciation
      section.se1.senseGroup                 one per part of speech
        h2.partOfSpeechTitle > span.partOfSpeech
        span.reg                             register (informal, ...)
        div.msDict.sense                     one per sense
          div.senseInnerWrapper
            span.definition                  the English definition
            span.cn_def                      the Chinese definition
            span.exampleGroup                the example pair
              em.example                     English example
              p.cn                          Chinese translation of it
            div.moreInformation              extra sentences
      span.etym ...                          etymology

93 distinct classes in total; 0 inline styles, 0 tables, 0 onclick -- the cleanest
source of the dictionaries examined so far.
"""
import argparse
import io
import json
import os
import re
import sys
import zipfile
from collections import Counter

# --------------------------------------------------------------- Yomitan SC
SC_WHITELIST = {
    "textAlign", "fontWeight", "fontSize", "color", "backgroundColor",
    "margin", "marginTop", "marginBottom", "marginLeft", "marginRight",
    "padding", "paddingTop", "paddingBottom", "paddingLeft", "paddingRight",
    "textDecoration", "textDecorationLine", "listStyleType", "verticalAlign",
    "clipPath", "wordBreak", "whiteSpace", "cursor", "fontStyle", "textShadow",
}


def sc(tag, content, cls=None, **kw):
    d = {}
    if cls:
        d["class"] = cls
    if kw:
        d["style"] = {k: v for k, v in kw.items() if k in SC_WHITELIST}
    node = {"tag": tag}
    if d:
        node["data"] = d
    if content is not None:
        node["content"] = content
    return node


def text(s):
    return s


def div(content, cls=None, **kw):
    return sc("div", content, cls, **kw)


def span(content, cls=None, **kw):
    return sc("span", content, cls, **kw)


def strip_tags(s):
    s = re.sub(r"<script\b[^>]*>.*?</script>", " ", s, flags=re.S | re.I)
    s = re.sub(r"<style\b[^>]*>.*?</style>", " ", s, flags=re.S | re.I)
    s = re.sub(r"<[^>]+>", " ", s)
    s = re.sub(r"\s+", " ", s)
    return s.strip()


# ------------------------------------------------------------ CSS
def generate_css():
    return """/* ODE 2024 -> Yomitan, generated by ode2yomitan */
[data-sc-class="ld"] { display:block; line-height:1.5; font-size:1em; color:var(--text-color,inherit); }
[data-sc-class="ld-entry"] { display:block; margin:0 0 7px; }
[data-sc-class="ld-hwd"] { font-weight:700; font-size:1.15em; color:var(--ld-head); }
[data-sc-class="ld-pron"] { color:var(--ld-text2); font-size:.92em; margin-left:.4em; }
[data-sc-class="ld-pos"] { font-style:italic; font-weight:600; color:var(--ld-pos); margin-left:.45em; }
[data-sc-class="ld-reg"] { font-size:.78em; color:var(--ld-reg); margin-left:.4em; }
[data-sc-class="ld-sense"] { display:block; margin:0 0 5px; padding-left:1.9em; position:relative; }
[data-sc-class="ld-snum"] { position:absolute; left:0; top:0; min-width:1.35em; color:var(--ld-frame); font-weight:700; }
[data-sc-class="ld-def"] { color:var(--ld-text); }
[data-sc-class="ld-defcn"] { display:block; color:var(--ld-zh); }
[data-sc-class="ld-ex"] { display:block; margin:1px 0 2px; color:var(--ld-text2); font-size:.95em; }
[data-sc-class="ld-excn"] { display:block; color:var(--ld-zh); font-size:.95em; }
[data-sc-class="ld-etym"] { display:block; font-size:.88em; color:var(--ld-dim); margin-top:3px; }
[data-sc-class="ld-more"] { display:block; font-size:.9em; color:var(--ld-text2); margin:2px 0 0; }
:root { --ld-pos:#3f86d6; --ld-reg:#cc7233; --ld-frame:#22a06b; --ld-zh:#a274e8; }
"""


# ------------------------------------------------------------- the parser
class Parser:
    def __init__(self):
        self.unknown = Counter()

    # -- tiny helpers over the raw html -------------------------------
    @staticmethod
    def _first(html, pattern):
        m = re.search(pattern, html, re.S | re.I)
        return m.group(1) if m else None

    def _cls_text(self, html, cls):
        """Text of the first element whose class list contains `cls`."""
        m = re.search(r'<(\w+)[^>]*class="[^"]*\b' + re.escape(cls) +
                      r'\b[^"]*"[^>]*>(.*?)</\1>', html, re.S | re.I)
        if not m:
            return None
        return strip_tags(m.group(2))

    @staticmethod
    def _balanced(html, start):
        """Given the index just past an opening <tag ...>, return the inner html.

        A non-greedy `.*?</tag>` stops at the first nested closing tag, which for
        div.entryPageContent (full of nested divs) truncated the entry to almost
        nothing -- that is why the first run parsed 0 of 3,000 entries. Count
        open/close of the same tag instead.
        """
        m = re.match(r"<(\w+)", html[start:])
        if not m:
            return None
        tag = m.group(1).lower()
        depth = 1
        pos = start
        for tok in re.finditer(r"<(/?)(\w+)[^>]*?(/?)>", html[start:]):
            closing, name, selfclose = tok.group(1), tok.group(2).lower(), tok.group(3)
            if name != tag or selfclose:
                continue
            if closing:
                depth -= 1
                if depth == 0:
                    return html[start:start + tok.start()]
            else:
                depth += 1
        return html[start:]

    def _cls_inner(self, html, cls):
        """Inner HTML of the first element whose class list contains `cls`."""
        for m in re.finditer(r'<(\w+)[^>]*\bclass="([^"]*)"[^>]*>', html, re.I):
            if cls in m.group(2).split():
                inner = self._balanced(html, m.end())
                if inner is not None:
                    return inner
        return None

    # -- entry --------------------------------------------------------
    def parse(self, key, html):
        body = self._cls_inner(html, "entryPageContent")
        if body is None:
            return None
        out = []
        head = self._cls_inner(body, "entryHeader")
        hwd = None
        pron = None
        if head:
            hwd = self._cls_text(head, "realTitle")
            pron = self._cls_text(head, "headpron")
            pron = re.sub(r"^Pronunciation:\s*", "", pron or "", flags=re.I).strip()
        if not hwd:
            hwd = key.strip()
        out.append(span(hwd, "ld-hwd"))
        if pron:
            out.append(span(pron, "ld-pron"))

        # every part-of-speech group. Two shapes exist: the normal one is
        # section.se1.senseGroup, but single-POS entries (most words) use a bare
        # div.onesection with no section wrapper. Handle both.
        groups = list(re.finditer(
            r'<section[^>]*class="[^"]*\bsenseGroup\b[^"]*"[^>]*>', body, re.I))
        if not groups:
            groups = list(re.finditer(
                r'<div[^>]*class="[^"]*\bonesection\b[^"]*"[^>]*>', body, re.I))
        if not groups:
            groups = [None]
        for gm in groups:
            g = body[gm.end():] if gm else body
            if gm:
                # the group runs to the next group start or the end of the body
                nxt = body.find("<", gm.end())
                g = self._balanced(body, gm.end())
            self._group(g or body, out)

        etym = self._cls_text(body, "etym")
        if etym:
            out.append(div(etym, "ld-etym"))

        if len(out) <= (2 if pron else 1):
            return None
        return div(out, "ld-entry")

    def _group(self, g, out):
        pos = self._cls_text(g, "partOfSpeech")
        reg = self._cls_text(g, "reg")
        if pos:
            out.append(span(pos, "ld-pos"))
        if reg:
            out.append(span(reg, "ld-reg"))
        n = 0
        # Two container shapes exist: the normal one wraps senses in
        # div.msDict.sense, but phrase/symbol entries use
        # div.onesection.phrase_more > div.senseInnerWrapper directly, with no
        # partOfSpeech at all (e.g. '!', '(Symbol: !)'). Handle both, and do not
        # require a POS -- 459 of the first 3,000 entries are of that shape.
        containers = list(re.finditer(
            r'<div[^>]*class="[^"]*\bmsDict\b[^"]*"[^>]*>', g, re.I))
        if containers:
            bounds = [m.start() for m in containers] + [len(g)]
            for i, m in enumerate(containers):
                n += 1
                self._sense(g[m.end():bounds[i + 1]], out, n)
        else:
            for sm in re.finditer(
                    r'<div[^>]*class="[^"]*\bsenseInnerWrapper\b[^"]*"[^>]*>(.*?)(?=<div[^>]*class="[^"]*\bsenseInnerWrapper\b|$)',
                    g, re.S | re.I):
                n += 1
                self._sense(sm.group(1), out, n)
            if n == 0:
                # a bare group with no wrapper at all
                self._sense(g, out, 1)

    def _sense(self, s, out, n):
        inner = self._cls_inner(s, "senseInnerWrapper") or s
        parts = [span(str(n), "ld-snum")]
        d = self._cls_text(inner, "definition")
        if d:
            parts.append(span(d, "ld-def"))
        cn = self._cls_text(inner, "cn_def")
        if cn:
            parts.append(span(cn, "ld-defcn"))
        # "See parent entry: -aemia" style stubs carry no definition; keep the
        # cross-reference so the entry is still useful rather than dropped.
        if not d:
            see = self._cls_text(inner, "see_text") or self._cls_text(s, "see_text")
            if see:
                parts.append(span(see, "ld-def"))
                d = see
        # the example pair
        eg = self._cls_inner(inner, "exampleGroup")
        if eg:
            en = self._cls_text(eg, "example")
            zh = self._cls_text(eg, "cn")
            if en:
                parts.append(div(en, "ld-ex"))
            if zh:
                parts.append(div(zh, "ld-excn"))
        more = self._cls_text(inner, "moreInformation")
        if more:
            parts.append(div(more, "ld-more"))
        if len(parts) > 1:
            out.append(div(parts, "ld-sense"))


# ------------------------------------------------------------------- main
def iter_records(path):
    from mdict_utils.reader import MDX
    m = MDX(path)
    for key, val in m.items():
        k = key.decode("utf-8", "replace") if isinstance(key, bytes) else str(key)
        b = val if isinstance(val, bytes) else str(val).encode()
        yield k, b.decode("utf-8", "replace")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("-i", required=True)
    ap.add_argument("-o", required=True)
    ap.add_argument("--mode", choices=("bilingual", "mono"), default="bilingual")
    ap.add_argument("--revision", default="2026.10.09")
    ap.add_argument("--limit", type=int, default=None)
    args = ap.parse_args()

    p = Parser()
    rows = []
    seq = 0
    n = 0
    skipped = 0
    for key, html in iter_records(args.i):
        n += 1
        if args.limit and n > args.limit:
            break
        try:
            content = p.parse(key, html)
        except Exception:
            content = None
        if content is None:
            skipped += 1
            continue
        gloss = [{"type": "structured-content", "content": content}]
        if args.mode == "mono":
            gloss = _strip_cn(gloss)
        rows.append([key.strip(), "", "", "", 10, gloss, seq, ""])
        seq += 1

    print(f"scanned {n:,} records, {len(rows):,} entries, {skipped:,} skipped")
    print("unknown/unparsed hints:", dict(p.unknown.most_common(8)))

    os.makedirs(args.o, exist_ok=True)
    idx = {
        "title": "Oxford Dictionary of English 2024",
        "format": 3, "revision": args.revision, "sequenced": True,
        "sourceLanguage": "en",
        "targetLanguage": "zh" if args.mode == "bilingual" else "en",
    }
    _write(args.o, idx, rows, p)


def _strip_cn(gloss):
    """Remove Chinese nodes for the monolingual build."""
    def walk(node):
        if isinstance(node, list):
            return [walk(x) for x in node
                    if not (isinstance(x, dict)
                            and "ld-defcn" in str((x.get("data") or {}).get("class", ""))
                            or (isinstance(x, dict)
                                and (x.get("data") or {}).get("class") == "ld-excn"))]
        if isinstance(node, dict) and "content" in node:
            node["content"] = walk(node["content"])
        return node
    return walk(gloss)


def _write(out, idx, rows, parser):
    css = generate_css()
    names = []
    batch = 10000
    for i in range(0, len(rows), batch):
        chunk = rows[i:i + batch]
        name = f"term_bank_{i // batch + 1}.json"
        payload = json.dumps(chunk, ensure_ascii=False, separators=(",", ":"))
        with io.open(os.path.join(out, name), "w", encoding="utf-8") as f:
            f.write(payload)
        names.append(name)
        print(f"   wrote {name} ({len(chunk):,} rows)")
    with io.open(os.path.join(out, "index.json"), "w", encoding="utf-8") as f:
        f.write(json.dumps(idx, ensure_ascii=False, indent=2))
    with io.open(os.path.join(out, "styles.css"), "w", encoding="utf-8") as f:
        f.write(css)
    tags = []
    with io.open(os.path.join(out, "tag_bank_1.json"), "w", encoding="utf-8") as f:
        f.write(json.dumps(tags, ensure_ascii=False))
    print(f"done: {len(rows):,} rows in {len(names)} bank(s)")


if __name__ == "__main__":
    main()
