
# ---------------------------------------------------------------------------
# CSS (all hooks via data-sc-class; every emitted class gets a rule)
# ---------------------------------------------------------------------------


def generate_css():
    return """/* LDOCE5++ Yomitan styles - generated by ldoce2yomitan v""" + VERSION + """ */
.gloss-sc { white-space: pre-wrap; }
.gloss-sc--structured-content { white-space: normal; }
[data-sc-class="ld"] { --ld-link:#0a66c2; --ld-head:#1c1e21; line-height:1.5; font-size:1em; color:#202124; display:block; }
[data-sc-class="ld-entry"] { display:block; }
[data-sc-class="ld-entry"] + [data-sc-class="ld-entry"] { border-top:1px solid rgba(128,128,128,.3); margin-top:8px; padding-top:8px; }
[data-sc-class="ld-empty"] { display:none; }

/* headword */
[data-sc-class="ld-head"] { display:block; margin:2px 0 6px; }
[data-sc-class="ld-hwd-wrap"] { font-size:1.28em; font-weight:700; color:var(--ld-head); }
[data-sc-class="ld-hwd"] { font:inherit; color:inherit; }
[data-sc-class="ld-hyp"] { color:#9aa0a6; padding:0 1px; }
[data-sc-class="ld-sup"] { font-size:.68em; vertical-align:super; color:#b3541e; font-weight:700; }
[data-sc-class="ld-pron"], [data-sc-class="ld-pronblk"], [data-sc-class="ld-pron-amevar"] { font-size:.92em; color:#444; margin-left:.45em; }
[data-sc-class="ld-pronblk"] { display:inline; }
[data-sc-class="ld-pron-amevar"] { color:#666; }
[data-sc-class="ld-pos"] { font-size:.88em; font-style:italic; color:#0b57a4; margin-left:.45em; font-weight:600; }
[data-sc-class="ld-level"] { color:#f0a020; margin-left:.5em; font-size:.85em; letter-spacing:1px; }
[data-sc-class="ld-freq"] { display:inline-block; margin-left:.25em; padding:0 4px; border-radius:3px; font-size:.72em; font-weight:600; background:rgba(11,87,164,.1); color:#0b57a4; border:1px solid rgba(11,87,164,.25); }
[data-sc-class="ld-sep"] { color:#9aa0a6; margin:0 .35em; }
[data-sc-class="ld-infl"] { font-size:.85em; color:#555; }
[data-sc-class="ld-infl-form"] { white-space:nowrap; }
[data-sc-class="ld-infl-lab"] { font-style:italic; opacity:.75; }

/* senses */
[data-sc-class="ld-sense"], [data-sc-class="ld-sense-cross"], [data-sc-class="ld-sense-merge"] { display:block; margin:0 0 7px; padding-left:1.9em; }
[data-sc-class="ld-subsense"] { display:block; margin:2px 0 3px; padding-left:1.6em; }
[data-sc-class="ld-runon"] { display:block; margin:2px 0 4px; padding-left:1.9em; color:#444; }
[data-sc-class="ld-phrventry"] { display:block; border-left:3px solid rgba(20,124,80,.35); margin:6px 0; padding:2px 0 2px .7em; }
[data-sc-class="ld-snum"] { display:inline-block; min-width:1.35em; margin-left:-1.9em; font-weight:700; color:#147c50; font-variant-numeric:tabular-nums; }
[data-sc-class="ld-gram"] { display:inline-block; font-size:.8em; font-weight:600; color:#0b57a4; background:rgba(11,87,164,.08); border:1px solid rgba(11,87,164,.22); border-radius:4px; padding:0 5px; margin:0 .35em 0 .1em; }
[data-sc-class="ld-geo"] { display:inline-block; font-size:.8em; font-weight:600; color:#8a3ffc; background:rgba(138,63,252,.07); border:1px solid rgba(138,63,252,.2); border-radius:4px; padding:0 5px; margin-right:.35em; }
[data-sc-class="ld-register"] { display:inline-block; font-size:.8em; font-weight:600; color:#b3541e; background:rgba(179,84,30,.08); border:1px solid rgba(179,84,30,.22); border-radius:4px; padding:0 5px; margin-right:.35em; }
[data-sc-class="ld-field"], [data-sc-class="ld-fieldxx"] { display:inline-block; font-size:.78em; font-weight:700; color:#5b6420; letter-spacing:.4px; margin-right:.35em; }
[data-sc-class="ld-act"] { display:inline-block; font-size:.78em; font-weight:700; letter-spacing:.3px; color:#147c50; background:rgba(20,124,80,.08); border:1px solid rgba(20,124,80,.25); border-radius:3px; padding:0 4px; margin-right:.35em; text-transform:uppercase; }
[data-sc-class="ld-actcn"] { font-size:.8em; color:#147c50; margin-right:.35em; }
[data-sc-class="ld-signpost"] { display:inline-block; font-weight:700; color:#444; font-size:.94em; margin-right:.3em; }

/* definitions and translations */
[data-sc-class="ld-def"] { display:block; margin:1px 0; font-size:1.02em; font-weight:500; }
[data-sc-class="ld-defcn"] { display:block; margin:1px 0 3px; font-weight:600; color:#6a3fa8; }
[data-sc-class="ld-zh"] { color:#6a3fa8; }
[data-sc-class="ld-en"] { color:inherit; font-weight:600; }
[data-sc-class="ld-gloss"] { color:#777; font-size:.95em; }
[data-sc-class="ld-grouptitle"] { font-weight:700; color:#147c50; }

/* examples */
[data-sc-class="ld-ex"], [data-sc-class="ld-ex-good"], [data-sc-class="ld-ex-bad"], [data-sc-class="ld-gramexa"], [data-sc-class="ld-colloexa"] { display:block; margin:1px 0 3px; padding-left:1.6em; text-indent:-1.6em; color:#3c4043; font-size:.97em; }
[data-sc-class="ld-ex"]::before, [data-sc-class="ld-gramexa"]::before, [data-sc-class="ld-colloexa"]::before { content:"\\2013\\00a0 "; color:#147c50; font-weight:700; }
[data-sc-class="ld-ex-good"]::before { content:"\\2713\\00a0 "; color:#147c50; font-weight:700; }
[data-sc-class="ld-ex-bad"]::before { content:"\\2717\\00a0 "; color:#c5221f; font-weight:700; }
[data-sc-class="ld-excn"] { display:block; padding-left:1.6em; text-indent:0; color:#6a3fa8; font-size:.95em; margin-bottom:2px; }
[data-sc-class="ld-propform"] { font-weight:700; color:#0b57a4; }
[data-sc-class="ld-hint"] { display:block; border-left:3px solid #f0a020; background:rgba(240,160,32,.08); padding:3px 8px; margin:4px 0; }
[data-sc-class="ld-hint-inline"] { color:#a06a00; font-style:italic; }
[data-sc-class="ld-dontsay"] { display:block; border-left:3px solid #c5221f; background:rgba(197,34,31,.07); padding:3px 8px; margin:4px 0; }
[data-sc-class="ld-warn"] { display:block; color:#c5221f; }

/* cross references */
[data-sc-class="ld-xref"], [data-sc-class="ld-xref-dead"] { font-weight:600; }
[data-sc-class="ld-xref-dead"] { color:#5f6368; text-decoration:underline dotted; }
[data-sc-class="ld-crossref"] { display:block; margin:2px 0 4px; color:#444; font-size:.96em; }
[data-sc-class="ld-syn"], [data-sc-class="ld-homophone"] { display:block; margin:2px 0; font-size:.96em; color:#3c4043; }
[data-sc-class="ld-synmark"] { display:inline-block; font-size:.72em; font-weight:700; color:#b3541e; border:1px solid rgba(179,84,30,.4); border-radius:3px; padding:0 3px; margin-right:.3em; }
[data-sc-class="ld-xrtype"] { font-style:italic; color:#5f6368; font-size:.9em; margin-right:.25em; }
[data-sc-class="ld-refhwd"] { font-weight:700; color:var(--ld-head); }
[data-sc-class="ld-deriv"] { font-weight:700; }
[data-sc-class="ld-lexvar"] { font-style:italic; }
[data-sc-class="ld-equiv"] { font-weight:600; color:#444; }
[data-sc-class="ld-thesref"] { font-weight:700; color:#147c50; }
[data-sc-class="ld-relatedwd"] { font-weight:600; }
[data-sc-class="ld-abbr"] { font-weight:600; }
[data-sc-class="ld-num"] { display:inline-block; min-width:1.2em; text-align:center; color:#888; }

/* collocations / thesaurus / grammar panels */
[data-sc-class="ld-collo"], [data-sc-class="ld-exp"] { font-weight:700; color:var(--ld-head); }
[data-sc-class="ld-colloin"] { font-weight:600; }
[data-sc-class="ld-nodew"] { font-weight:600; color:#0b57a4; }
[data-sc-class="ld-b"] { font-weight:700; }
[data-sc-class="ld-it"] { font-style:italic; }
[data-sc-class="ld-collocate"] { display:block; margin:3px 0; padding-left:.4em; }
[data-sc-class="ld-exponent"] { display:block; margin:4px 0; padding-left:.4em; }
[data-sc-class="ld-section"] { display:block; margin:4px 0 2px; }
[data-sc-class="ld-psub"], [data-sc-class="ld-phead"] { display:block; font-weight:800; color:#147c50; margin:4px 0 2px; }
[data-sc-class="ld-expl"] { display:block; margin:3px 0; }
[data-sc-class="ld-expr"] { font-weight:700; }
[data-sc-class="ld-frequency"] { display:block; padding:4px; }
[data-sc-class="ld-spokensect"] { display:block; margin:6px 0; }
[data-sc-class="ld-obj"] { font-style:italic; }
[data-sc-class="ld-block"] { display:block; }
[data-sc-class="ld-para"] { display:block; margin:2px 0; }

/* panels */
[data-sc-class="ld-panel"], [data-sc-class="ld-panel-corpus"], [data-sc-class="ld-panel-wf"], [data-sc-class="ld-panel-etym"] { display:block; margin:5px 0 6px; }
[data-sc-class="ld-panel-sum"] { cursor:pointer; font-weight:700; color:var(--ld-head); list-style:none; padding:1px 0 1px 1.1em; position:relative; user-select:none; }
[data-sc-class="ld-panel-sum"]::-webkit-details-marker { display:none; }
[data-sc-class="ld-panel-sum"]::before { content:""; position:absolute; left:0; top:50%; border-top:.32em solid transparent; border-bottom:.32em solid transparent; border-left:.48em solid #147c50; transform:translateY(-50%); transition:transform .12s; }
[data-sc-class="ld-panel"][open] > [data-sc-class="ld-panel-sum"]::before, [data-sc-class="ld-panel-corpus"][open] > [data-sc-class="ld-panel-sum"]::before, [data-sc-class="ld-panel-wf"][open] > [data-sc-class="ld-panel-sum"]::before, [data-sc-class="ld-panel-etym"][open] > [data-sc-class="ld-panel-sum"]::before { transform:translateY(-50%) rotate(90deg); }
[data-sc-class="ld-panel-title"] { color:#147c50; }
[data-sc-class="ld-panel-title-zh"] { margin-left:.5em; font-size:.85em; color:#6a3fa8; font-weight:600; }
[data-sc-class="ld-panel-body"] { border-left:3px solid rgba(20,124,80,.35); background:rgba(20,124,80,.05); border-radius:0 4px 4px 0; padding:4px 8px; margin-top:3px; }
[data-sc-class="ld-panel-boxbody"] { display:block; }
[data-sc-class="ld-panel-corpus"] > [data-sc-class="ld-panel-body"] { background:rgba(11,87,164,.05); border-left-color:rgba(11,87,164,.35); }
[data-sc-class="ld-panel-etym"] > [data-sc-class="ld-panel-sum"]::before { border-left-color:#b3541e; }
[data-sc-class="ld-panel-wf"] > [data-sc-class="ld-panel-body"] { display:flex; flex-direction:column; gap:2px; }
[data-sc-class="ld-wf-group"] { display:block; }
[data-sc-class="ld-wf-pos"] { font-style:italic; font-weight:700; color:#0b57a4; margin-right:.3em; font-size:.9em; }
[data-sc-class="ld-wf-word"] { font-weight:600; }
[data-sc-class="ld-wf-root"] { color:#5f6368; border-bottom:1px dotted #999; }

/* corpus list */
[data-sc-class="ld-exagroup"] { display:block; margin:3px 0; }
[data-sc-class="ld-exagroup-title"] { font-weight:700; color:#147c50; margin-bottom:2px; }
[data-sc-class="ld-corpulist"] { list-style:none; margin:0 0 4px; padding:0; }
[data-sc-class="ld-corpexa"], [data-sc-class="ld-corpexa-corpus"], [data-sc-class="ld-corpexa-dics"], [data-sc-class="ld-corpexa-encyc"], [data-sc-class="ld-corpexa-online"], [data-sc-class="ld-corpexa-phrases"] { display:list-item; padding-left:1.2em; text-indent:-1.2em; margin:1px 0; font-size:.96em; color:#3c4043; }
[data-sc-class="ld-corpexa"]::before, [data-sc-class="ld-corpexa-corpus"]::before, [data-sc-class="ld-corpexa-dics"]::before, [data-sc-class="ld-corpexa-encyc"]::before, [data-sc-class="ld-corpexa-online"]::before, [data-sc-class="ld-corpexa-phrases"]::before { content:"\\2022\\00a0 "; color:#9aa0a6; }

/* lists and tables (usage panels) */
[data-sc-class="ld-list"] { margin:2px 0 4px 1.4em; padding:0; }
[data-sc-class="ld-table"] { border-collapse:collapse; margin:4px 0; width:auto; }
[data-sc-class="ld-td"], [data-sc-class="ld-th"] { border:1px solid rgba(128,128,128,.35); padding:2px 6px; font-size:.95em; text-align:left; }
[data-sc-class="ld-th"] { background:rgba(20,124,80,.08); font-weight:700; }

/* etymology */
[data-sc-class="ld-origin"] { font-style:italic; font-weight:600; }
[data-sc-class="ld-century"] { color:#5f6368; font-size:.9em; }
[data-sc-class="ld-tran"] { font-style:italic; color:#444; }
[data-sc-class="ld-lang"] { font-style:italic; font-weight:600; color:#0b57a4; }

/* links */
[data-sc-class="ld"] a { color:var(--ld-link); font-weight:600; text-decoration:none; }
[data-sc-class="ld"] a:hover { text-decoration:underline; }

/* topics / misc */
[data-sc-class="ld-topics"], [data-sc-class="ld-topics-body"] { display:block; margin:4px 0; }

@media (prefers-color-scheme: dark) {
  [data-sc-class="ld"] { color-scheme:dark; color:#dadce0; --ld-head:#e8eaed; --ld-link:#8ab4f8; }
  [data-sc-class="ld-pron"], [data-sc-class="ld-pronblk"], [data-sc-class="ld-pron-amevar"], [data-sc-class="ld-infl"] { color:#b0b3b8; }
  [data-sc-class="ld-zh"], [data-sc-class="ld-defcn"], [data-sc-class="ld-excn"], [data-sc-class="ld-panel-title-zh"] { color:#c9a6ff; }
  [data-sc-class="ld-crossref"], [data-sc-class="ld-ex"], [data-sc-class="ld-ex-good"], [data-sc-class="ld-ex-bad"], [data-sc-class="ld-gramexa"], [data-sc-class="ld-colloexa"], [data-sc-class="ld-runon"], [data-sc-class="ld-signpost"], [data-sc-class="ld-corpexa"], [data-sc-class="ld-corpexa-corpus"], [data-sc-class="ld-corpexa-dics"], [data-sc-class="ld-corpexa-encyc"], [data-sc-class="ld-corpexa-online"], [data-sc-class="ld-corpexa-phrases"] { color:#bdc1c6; }
  [data-sc-class="ld-gloss"] { color:#9aa0a6; }
  [data-sc-class="ld-td"], [data-sc-class="ld-th"] { border-color:rgba(160,160,160,.4); }
}
"""


# ---------------------------------------------------------------------------
# Tag bank
# ---------------------------------------------------------------------------

TAG_NOTES_ZH = {
    "noun": "名词", "verb": "动词", "adj": "形容词", "adv": "副词", "pron": "代词",
    "prep": "介词", "conj": "连词", "excl": "感叹词", "det": "限定词", "num": "数词",
    "modal": "情态动词", "aux": "助动词", "linking-v": "连系动词", "phrasal-v": "短语动词",
    "prefix": "前缀", "suffix": "后缀", "combining-form": "组合形式", "abbr": "缩写",
    "symb": "符号", "idiom": "习语", "def-article": "定冠词", "indef-article": "不定冠词",
    "ordinal-num": "序数词", "inf-marker": "不定式标记", "short-form": "缩略形式",
    "redirect": "重定向条目", "non-lemma": "词形变化/别名",
    "S1": "口语最高频词", "S2": "口语高频词", "S3": "口语常用词",
    "W1": "书面最高频词", "W2": "书面高频词", "W3": "书面常用词",
}
TAG_NOTES_EN = {
    "noun": "Noun", "verb": "Verb", "adj": "Adjective", "adv": "Adverb",
    "pron": "Pronoun", "prep": "Preposition", "conj": "Conjunction",
    "excl": "Exclamation", "det": "Determiner", "num": "Number",
    "modal": "Modal Verb", "aux": "Auxiliary Verb", "linking-v": "Linking Verb",
    "phrasal-v": "Phrasal Verb", "prefix": "Prefix", "suffix": "Suffix",
    "combining-form": "Combining Form", "abbr": "Abbreviation", "symb": "Symbol",
    "idiom": "Idiom", "def-article": "Definite Article",
    "indef-article": "Indefinite Article", "ordinal-num": "Ordinal Number",
    "inf-marker": "Infinitive Marker", "short-form": "Short Form",
    "redirect": "Redirect entry", "non-lemma": "Non-lemma form",
    "S1": "Spoken frequency S1", "S2": "Spoken frequency S2", "S3": "Spoken frequency S3",
    "W1": "Written frequency W1", "W2": "Written frequency W2", "W3": "Written frequency W3",
}


def build_tag_bank(ui_zh):
    notes = TAG_NOTES_ZH if ui_zh else TAG_NOTES_EN
    tags = []
    seen = set()
    order = 1
    for name in POS_TAG_MAP.values():
        if name in seen:
            continue
        seen.add(name)
        tags.append([name, "partOfSpeech", order, notes.get(name, name), 0])
        order += 1
    order = 30
    for s in ("S1", "S2", "S3", "W1", "W2", "W3"):
        tags.append([s, "frequency", order, notes.get(s, s), 0])
        order += 1
    tags.append(["redirect", "search", -5, notes["redirect"], 0])
    tags.append(["non-lemma", "partOfSpeech", 100, notes["non-lemma"], 0])
    return tags


# ---------------------------------------------------------------------------
# Entry-level tag extraction (cheap regex scan, no full DOM)
# ---------------------------------------------------------------------------

POS_SCAN_RE = re.compile(r'<span class="lm5pp_POS[^"]*">(.*?)</span>', re.S)
FREQ_SCAN_RE = re.compile(r'<span class="[^"]*\bFREQ\b[^"]*">\s*([SW][123])\s*<')


def extract_tags(content):
    pos_tokens = POS_SCAN_RE.findall(content)
    freq_tokens = FREQ_SCAN_RE.findall(content)
    return pos_tokens, freq_tokens


def pos_tags_rules(pos_tokens, freq_tokens):
    tags = []
    rules = []
    for token in pos_tokens:
        text = re.sub(r"<[^>]+>", " ", token)
        text = strip_invisible(collapse_ws(text)).strip().lower()
        text = text.strip(" .;")
        for part in [text] + re.split(r"[,;]", text):
            part = part.strip(" .()")
            if not part:
                continue
            tag = POS_TAG_MAP.get(part)
            if tag and tag not in tags:
                tags.append(tag)
            rule = POS_RULE_MAP.get(part, "")
            if rule and rule not in rules:
                rules.append(rule)
        if len(tags) >= 4:
            break
    for f in dict.fromkeys(freq_tokens):
        if f not in tags:
            tags.append(f)
    return " ".join(tags[:6]), " ".join(rules[:4])


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

SC_TAG_KEYS = {
    "br": {"tag", "data"},
    **{tag: {"tag", "content", "data", "lang"}
       for tag in ("ruby", "rt", "rp", "table", "thead", "tbody", "tfoot", "tr")},
    **{tag: {"tag", "content", "data", "colSpan", "rowSpan", "style", "lang"}
       for tag in ("td", "th")},
    **{tag: {"tag", "content", "data", "style", "title", "open", "lang"}
       for tag in ("span", "div", "ol", "ul", "li", "details", "summary")},
    "img": {"tag", "data", "path", "width", "height", "title", "alt",
            "description", "pixelated", "imageRendering", "appearance",
            "background", "collapsed", "collapsible", "verticalAlign",
            "border", "borderRadius", "sizeUnits"},
    "a": {"tag", "content", "href", "lang"},
}


def sc_shape_error(value, path="content"):
    if isinstance(value, str):
        return ""
    if isinstance(value, list):
        for i, item in enumerate(value):
            err = sc_shape_error(item, f"{path}[{i}]")
            if err:
                return err
        return ""
    if not isinstance(value, dict):
        return f"{path} must be string/array/object"
    tag = value.get("tag")
    if tag not in SC_TAG_KEYS:
        return f"{path}.tag unsupported: {tag!r}"
    extra = set(value) - SC_TAG_KEYS[tag]
    if extra:
        return f"{path}.{sorted(extra)[0]} not allowed on <{tag}>"
    data = value.get("data")
    if data is not None and (not isinstance(data, dict)
                             or any(not isinstance(v, str) for v in data.values())):
        return f"{path}.data must have string values"
    if tag == "a":
        href = value.get("href")
        if not isinstance(href, str) or not re.match(r"^(?:\?|https?:)", href):
            return f"{path}.href invalid"
    if "content" in value:
        return sc_shape_error(value["content"], f"{path}.content")
    return ""


def term_row_shape_error(row):
    if not isinstance(row, list) or len(row) != 8:
        return "row must have 8 fields"
    for i in (0, 1, 2, 3, 7):
        if not isinstance(row[i], str):
            return f"field {i} must be string"
    if not row[0].strip():
        return "empty expression"
    if isinstance(row[4], bool) or not isinstance(row[4], (int, float)):
        return "score must be number"
    if not isinstance(row[5], list) or not row[5]:
        return "glossary must be non-empty array"
    for j, item in enumerate(row[5]):
        if isinstance(item, list):
            if (len(item) != 2 or not isinstance(item[0], str)
                    or not isinstance(item[1], list)
                    or any(not isinstance(x, str) for x in item[1])):
                return f"glossary[{j}] invalid [term, rules] redirect"
            continue
        if not isinstance(item, dict):
            return f"glossary[{j}] must be object/array/string"
        if item.get("type") == "structured-content":
            if set(item) != {"type", "content"}:
                return f"glossary[{j}] invalid SC wrapper keys"
            err = sc_shape_error(item["content"], f"glossary[{j}].content")
            if err:
                return err
        elif item.get("type") == "text":
            if set(item) != {"type", "text"} or not isinstance(item["text"], str):
                return f"glossary[{j}] invalid text item"
        else:
            return f"glossary[{j}] unsupported glossary item"
    if isinstance(row[6], bool) or not isinstance(row[6], int):
        return "sequence must be int"
    return ""


def collect_sc_classes(value, found):
    if isinstance(value, list):
        for item in value:
            collect_sc_classes(item, found)
    elif isinstance(value, dict):
        cls = (value.get("data") or {}).get("class")
        if cls:
            found.update(cls.split())
        for key, item in value.items():
            if key != "data":
                collect_sc_classes(item, found)


def iter_sc_links(value):
    if isinstance(value, list):
        for item in value:
            yield from iter_sc_links(item)
    elif isinstance(value, dict):
        if value.get("tag") == "a":
            yield value
        for key, item in value.items():
            if key != "data":
                yield from iter_sc_links(item)


def validate_package(zip_path, term_index, revision, mode):
    errors = []
    stats = Counter()
    used_classes = set()
    with zipfile.ZipFile(zip_path) as zf:
        names = zf.namelist()
        for required in ("index.json", "styles.css", "tag_bank_1.json"):
            if required not in names:
                errors.append(f"missing {required}")
        index = json.loads(zf.read("index.json").decode("utf-8"))
        if index.get("format") != 3:
            errors.append("index.format must be 3")
        if index.get("sequenced") is not True:
            errors.append("index.sequenced must be true")
        if index.get("sourceLanguage") != "en":
            errors.append("index.sourceLanguage must be en")
        expect_target = "zh" if mode == "bilingual" else "en"
        if index.get("targetLanguage") != expect_target:
            errors.append(f"index.targetLanguage must be {expect_target}")
        if str(index.get("revision")) != str(revision):
            errors.append("index.revision mismatch")
        banks = sorted(n for n in names if re.fullmatch(r"term_bank_\d+\.json", n))
        if not banks:
            errors.append("no term banks")
            return errors, stats
        stats["term_banks"] = len(banks)
        all_terms = set()
        for bank in banks:
            rows = json.loads(zf.read(bank).decode("utf-8"))
            stats["rows"] += len(rows)
            for row in rows:
                err = term_row_shape_error(row)
                if err:
                    errors.append(f"{bank} {row[0]!r}: {err}")
                    if len(errors) > 40:
                        return errors, stats
                    continue
                all_terms.add(row[0])
                for item in row[5]:
                    if isinstance(item, list):
                        stats["redirect_items"] += 1
                        if item[0] not in all_terms and item[0] not in term_index:
                            errors.append(
                                f"{bank} {row[0]!r}: dangling redirect -> {item[0]!r}")
                    elif isinstance(item, dict) and item.get("type") == "structured-content":
                        collect_sc_classes(item["content"], used_classes)
                        for link in iter_sc_links(item["content"]):
                            href = link.get("href") or ""
                            if href.startswith("?query="):
                                stats["query_links"] += 1
                                target = unquote(href[len("?query="):].split("&")[0])
                                if target not in all_terms and target not in term_index:
                                    stats["dangling_links"] += 1
                                    if stats["dangling_links"] <= 20:
                                        errors.append(
                                            f"{bank} {row[0]!r}: dangling query link -> {target!r}")
        css = zf.read("styles.css").decode("utf-8") if "styles.css" in names else ""
        defined = set()
        for m in re.findall(r'\[data-sc-class="([^"]+)"\]', css):
            defined.update(m.split())
        for m in re.findall(r'\[data-sc-class~="([^"]+)"\]', css):
            defined.update(m.split())
        missing = used_classes - defined
        if missing:
            errors.append("CSS missing selectors for: " + ", ".join(sorted(missing)))
        if mode == "mono":
            blob = zf.read(banks[0]).decode("utf-8")
            if CJK_RE.search(blob):
                errors.append("mono build contains CJK text")
    return errors, stats


# ---------------------------------------------------------------------------
# Build pipeline
# ---------------------------------------------------------------------------


def build(input_path, output_dir, mode="bilingual", revision=None, test_words=None,
          open_panels=False, keep_json=False, validate=True, show_progress=True,
          limit=None):
    start = time.time()
    os.makedirs(output_dir, exist_ok=True)
    revision = revision or date.today().strftime("%Y.%m.%d")
    source_revision = infer_source_revision(input_path)

    debug = bool(test_words)
    test_set = None
    if debug:
        test_set = {w.strip().casefold() for w in re.split(r"[,;，、]", test_words) if w.strip()}

    print("[*] Pass A: collecting headword index ...")
    term_index = TermIndex()
    n_lines = count_lines(input_path)
    alias_rows = []
    seen_kinds = Counter()
    est_records = max(n_lines // 2, 1)
    for key, content in tqdm(iter_records(input_path), total=est_records,
                             desc="index", disable=not show_progress):
        k = strip_invisible(key).strip()
        if not k:
            continue
        kind, target = classify_record(k, content)
        seen_kinds[kind] += 1
        if kind == "entry":
            term_index.add(k)
        elif kind == "redirect":
            alias_rows.append((k, target))
    print(f"[OK] Pass A: entries={seen_kinds['entry']} unique={len(term_index.exact)} "
          f"redirects={seen_kinds['redirect']} skipped={seen_kinds['skip']}")

    print("[*] Pass B: rendering structured content ...")
    renderer = LdoceRenderer(term_index, mode=mode, open_panels=open_panels)
    term_bank = []
    file_index = 1
    sequence = 0
    generated = []
    rendered_keys = set()
    key_rules = {}
    stats = Counter()

    def save_bank(rows, idx):
        path = os.path.join(output_dir, f"term_bank_{idx}.json")
        data = sanitize_strings(rows)
        with io.open(path, "w", encoding="utf-8") as handle:
            if debug:
                json.dump(data, handle, ensure_ascii=False, indent=1)
            else:
                json.dump(data, handle, ensure_ascii=False, separators=(",", ":"))
        generated.append(path)

    def flush_if_full():
        nonlocal term_bank, file_index
        if len(term_bank) >= TERM_BANK_BATCH:
            save_bank(term_bank, file_index)
            print(f"    -> wrote term_bank_{file_index}.json ({len(term_bank)} rows)")
            term_bank = []
            file_index += 1

    processed = 0
    for key, content in tqdm(iter_records(input_path), total=est_records,
                             desc="render", disable=not show_progress):
        processed += 1
        k = strip_invisible(key).strip()
        if not k:
            continue
        kind, _target = classify_record(k, content)
        if kind != "entry":
            continue
        if debug and k.casefold() not in test_set:
            continue
        try:
            nodes = renderer.render_record(k, content)
        except Exception as exc:  # noqa: BLE001
            stats["render_errors"] += 1
            if stats["render_errors"] <= 8:
                print(f"[WARN] render error {k!r}: {exc!r}")
            continue
        if not nodes or not sc_has_text(nodes):
            stats["empty_records"] += 1
            continue
        pos_tokens, freq_tokens = extract_tags(content)
        tags, rules = pos_tags_rules(pos_tokens, freq_tokens)
        rendered_keys.add(k)
        key_rules[k] = rules
        gloss = [{"type": "structured-content",
                  "content": sc("div", nodes, cls="ld")}]
        term_bank.append([k, "", tags, rules, ENTRY_SCORE, gloss, sequence, ""])
        sequence += 1
        flush_if_full()
        if limit and len(rendered_keys) >= limit:
            break

    term_index.finalize_rendered(rendered_keys)

    # ---- redirect resolution ----------------------------------------------
    target_map = {}
    for word, target in alias_rows:
        if target and target != word:
            target_map.setdefault(word, []).append(target)

    def resolve_alias(word):
        out = []
        seen = set()
        stack = list(target_map.get(word, []))
        while stack:
            current = stack.pop()
            if current in seen:
                continue
            seen.add(current)
            if current in rendered_keys:
                out.append(current)
            elif current in target_map:
                stack.extend(target_map[current])
        return list(dict.fromkeys(out))

    alias_rendered = 0
    for word in sorted(target_map):
        if word in rendered_keys:
            continue
        targets = resolve_alias(word)
        if not targets:
            continue
        rules = " ".join(dict.fromkeys(
            tok for t in targets for tok in (key_rules.get(t) or "").split()))
        content_gloss = [[t, ["redirect"]] for t in targets]
        term_bank.append([word, "", "non-lemma", rules, REDIRECT_SCORE,
                          content_gloss, sequence, ""])
        sequence += 1
        alias_rendered += 1
        flush_if_full()
    if term_bank:
        save_bank(term_bank, file_index)
        print(f"    -> wrote term_bank_{file_index}.json ({len(term_bank)} rows)")

    # ---- metadata ----------------------------------------------------------
    ui_zh = mode == "bilingual"
    desc_bits = ["Longman Dictionary of Contemporary English 5++ V2.15",
                 "朗文当代高级英语辞典 · 双语增强版",
                 f"converter v{VERSION}"]
    if source_revision:
        desc_bits.append(f"source {source_revision}")
    index_data = {
        "title": "LDOCE5++ (LM5pp)",
        "format": 3,
        "revision": revision,
        "sequenced": True,
        "author": AUTHOR,
        "url": PROJECT_URL,
        "description": "；".join(desc_bits) if ui_zh else "; ".join(desc_bits),
        "attribution": ("Longman Dictionary of Contemporary English (Pearson); "
                        "LM5pp HTML edition; data: " + SOURCE_FORUM_URL),
        "sourceLanguage": "en",
        "targetLanguage": "zh" if ui_zh else "en",
    }
    index_path = os.path.join(output_dir, "index.json")
    with io.open(index_path, "w", encoding="utf-8") as handle:
        json.dump(index_data, handle, ensure_ascii=False,
                  indent=1 if debug else None,
                  separators=None if debug else (",", ":"))
    generated.append(index_path)
    tag_path = os.path.join(output_dir, "tag_bank_1.json")
    with io.open(tag_path, "w", encoding="utf-8") as handle:
        json.dump(build_tag_bank(ui_zh), handle, ensure_ascii=False,
                  indent=1 if debug else None,
                  separators=None if debug else (",", ":"))
    generated.append(tag_path)
    css_path = os.path.join(output_dir, "styles.css")
    with io.open(css_path, "w", encoding="utf-8") as handle:
        handle.write(generate_css())
    generated.append(css_path)

    zip_name = (f"LDOCE5pp_Yomitan_{date.today().strftime('%Y.%m.%d')}"
                + ("" if ui_zh else "_EN") + ("_DEBUG" if debug else "") + ".zip")
    zip_path = os.path.join(output_dir, zip_name)
    print(f"[*] Compressing {zip_name} ...")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
        for path in generated:
            if os.path.exists(path):
                zf.write(path, os.path.basename(path))

    if renderer.unknown_classes:
        print("[*] Top unknown classes kept generically:")
        for name, cnt in renderer.unknown_classes.most_common(25):
            print(f"      {cnt:>9}  {name}")

    print("\n=== Stats ===")
    print(f"[*] Records scanned: {processed}")
    print(f"[*] Rendered entries: {len(rendered_keys)}")
    print(f"[*] Redirect rows: {alias_rendered} (alias keys: {len(target_map)})")
    print(f"[*] Empty after render: {stats['empty_records']}")
    print(f"[*] Render errors: {stats['render_errors']}")
    print(f"[*] Query links: live={renderer.stats['links_live']} "
          f"demoted={renderer.stats['links_dead']}")
    print(f"[*] Elapsed: {time.time() - start:.1f}s")

    if validate:
        print("[*] Validating package ...")
        errors, vstats = validate_package(zip_path, term_index, revision, mode)
        print(f"[*] Validator: rows={vstats['rows']} banks={vstats['term_banks']} "
              f"query_links={vstats['query_links']} dangling={vstats['dangling_links']} "
              f"redirect_items={vstats['redirect_items']}")
        if errors:
            print("[FAIL] Validation errors:")
            for err in errors[:60]:
                print("   - " + err)
        else:
            print("[OK] Validation passed.")
    if not keep_json:
        for path in list(generated):
            if os.path.basename(path).startswith("term_bank_"):
                try:
                    os.remove(path)
                except OSError:
                    pass
    print(f"[OK] Dictionary package: {zip_path}")
    return zip_path


def infer_source_revision(path):
    m = re.search(r"(20\d{6})(\d{4,6})?", os.path.basename(str(path)))
    return m.group(0) if m else ""


def main(argv=None):
    import argparse
    parser = argparse.ArgumentParser(description="LDOCE5++ (LM5pp) -> Yomitan dictionary")
    parser.add_argument("-i", "--input", required=True, help="MDX file or extracted .mdx.txt")
    parser.add_argument("-o", "--output", default="./yomitan_ldoce", help="Output directory")
    parser.add_argument("-m", "--mode", choices=("bilingual", "mono"), default="bilingual")
    parser.add_argument("--revision", default=None)
    parser.add_argument("--test-words", default=None,
                        help="Debug build restricted to these comma-separated headwords")
    parser.add_argument("--open-panels", action="store_true")
    parser.add_argument("--keep-json", action="store_true")
    parser.add_argument("--skip-validation", action="store_true")
    parser.add_argument("--no-progress", action="store_true")
    parser.add_argument("--limit", type=int, default=None,
                        help="Render at most N entries (smoke testing)")
    args = parser.parse_args(argv)
    input_path = prepare_input(args.input)
    build(
        input_path,
        args.output,
        mode=args.mode,
        revision=args.revision,
        test_words=args.test_words,
        open_panels=args.open_panels,
        keep_json=args.keep_json,
        validate=not args.skip_validation,
        show_progress=not args.no_progress,
        limit=args.limit,
    )


if __name__ == "__main__":
    main()
